### ISSUE TITLE
Require can be converted to custom Error code

### ISSUE THREAD

**Issue by allwin199** [pimlicolabs/erc20-paymaster#12]
Custom error codes can be used instead of strings.

https://github.com/pimlicolabs/erc20-paymaster-contracts/blob/60c3ea1c2d75069f9aa7f8d35bc08545a2edb34b/src/PimlicoERC20Paymaster.sol#L67-L70

Suggested Change:
```js
error PimlicoERC20Paymaster__PriceMarkUpTooHigh();
```
```js
if(_priceMarkup >= 120e4){
   revert PimlicoERC20Paymaster__PriceMarkUpTooHigh();
}
```

By using custom error codes instead of strings, less `gas` is used.

**Comment by worksofallwin** [comment]
If this change is necessary, I would like to work on this.
