### ISSUE TITLE
Named Imports can be used.

### ISSUE THREAD

**Issue by allwin199** [pimlicolabs/erc20-paymaster#13]
https://github.com/pimlicolabs/erc20-paymaster-contracts/blob/60c3ea1c2d75069f9aa7f8d35bc08545a2edb34b/src/PimlicoERC20Paymaster.sol#L8

Suggested Change:
```
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol"
```
Which can improve readability and also destruct only the necessary code.

**Comment by worksofallwin** [comment]
If this is necessary, I would like to raise a PR.
